export const projectsData = {
  stats: {
    total: 124,
    active: 82,
    completed: 40,
    onHold: 2,
  },
  projects: [
    {
      name: "Project Phoenix",
      team: "Developers Team, editor",
      creator: "Olivia Rhye",
      lead: "Lana Steiner",
      progress: 75,
      updated: "2 days ago",
    },
    {
      name: "Marketing Campaign",
      team: "Marketing Team",
      creator: "Phoenix Baker",
      lead: "Candice Wu",
      progress: 40,
      updated: "5 days ago",
    },
    {
      name: "Mobile App Redesign",
      team: "Design Team",
      creator: "Natali Craig",
      lead: "Drew Cano",
      progress: 90,
      updated: "yesterday",
    },
    {
      name: "New Website Launch",
      team: "Developers Team",
      creator: "Orlando Diggs",
      lead: "Kate Morrison",
      progress: 15,
      updated: "10 days ago",
    },
    {
      name: "API Integration",
      team: "Engineering",
      creator: "Koray Okumus",
      lead: "Andi Lane",
      progress: 60,
      updated: "3 days ago",
    },
  ],
};
